# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemRoadCalculatorDialog
                                 A QGIS plugin
 Calculate slope and aspect road lines using DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-03
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Dmitry D.
        email                : dmitrdobr@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.core import (
    QgsRasterLayer,
    QgsMapLayerProxyModel,
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dem_road_calculator_dialog_base.ui'))


class DemRoadCalculatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DemRoadCalculatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.mMapLayerComboBox_lines.setFilters(QgsMapLayerProxyModel.LineLayer) # загрузка фильтра слоев в QgsMapLayerComboBox
        self.mMapLayerComboBox_DEM.setFilters(QgsMapLayerProxyModel.RasterLayer) # загрузка фильтра слоев в QgsMapLayerComboBox

        self.mMapLayerComboBox_DEM.layerChanged.connect(self.RasterDemLayerChanged)
        self.RasterDemLayerChanged()

        self.checkBox_val_hgt.toggled.connect(self.lineEdit_val_hgt.setEnabled)
        self.checkBox_val_slope.toggled.connect(self.lineEdit_val_slope.setEnabled)
        self.checkBox_val_aspect.toggled.connect(self.lineEdit_val_aspect.setEnabled)
    
    def RasterDemLayerChanged(self):
        self.comboBox_band.clear()

        l = self.mMapLayerComboBox_DEM.currentLayer()

        if (type(l) is QgsRasterLayer):
            for i in range(l.bandCount()):
                self.comboBox_band.addItem(str(i+1))
    
    def setGUIEnabled(self, flag):
        # self.tabWidget.widget(0).setEnabled(flag)
        self.pushButton_start.setEnabled(flag)
        pass
